"""ORM models package. Importing it registers all tables on ``Base.metadata``."""
from app.models.enums import (
    AccountPlatform,
    AccountType,
    AssetKind,
    DisposalKind,
    FiscalYearStatus,
    ImportStatus,
    IncomeCategory,
    SummarySource,
    TransactionType,
)
from app.models.orm import (
    Account,
    Asset,
    Disposal,
    FiscalYear,
    FiscalYearSummary,
    ImportBatch,
    IncomeEvent,
    Lot,
    LotConsumption,
    PriceQuote,
    TaxBracket,
    Transaction,
)

__all__ = [
    "Account",
    "AccountPlatform",
    "AccountType",
    "Asset",
    "AssetKind",
    "Disposal",
    "DisposalKind",
    "FiscalYear",
    "FiscalYearStatus",
    "FiscalYearSummary",
    "ImportBatch",
    "ImportStatus",
    "IncomeEvent",
    "IncomeCategory",
    "Lot",
    "LotConsumption",
    "PriceQuote",
    "SummarySource",
    "TaxBracket",
    "Transaction",
    "TransactionType",
]
